#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: lscr.io/linuxserver/prowlarr
  # -- image tag
  tag: ""
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8989

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    hosts:
      - host: prowlarr.k8s.firekatt.ca
        paths:
          - path: /
            pathType: Prefix

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 2Gi

initContainers:
  update-volume-permission:
    name: update-volume-permission
    image: busybox
    command: ["sh", "-c", "chown -R 568:568 /config"]
    volumeMounts:
      - name: config
        mountPath: /config
    securityContext:
      runAsUser: 0
      