#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/geek-cookbook/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: lscr.io/linuxserver/sabnzbd
  # -- image tag
  tag: 4.5.1
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  HOST_WHITELIST_ENTRIES: "sabnzbd.k8s.firekatt.ca, sabnzbd.app-media"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    hosts:
      - host: sabnzbd.k8s.firekatt.ca
        paths:
          - path: /
            pathType: Prefix

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 2Gi

  media:
    enabled: true
    mountPath: /media
    type: nfs
    server: 10.0.1.241
    path: /volume2/media

  downloads:
    enabled: false
    mountPath: /downloads

initContainers:
  update-volume-permission:
    name: update-volume-permission
    image: busybox
    command: ["sh", "-c", "chown -R 568:568 /config"]
    volumeMounts:
      - name: config
        mountPath: /config
    securityContext:
      runAsUser: 0
      