homepage:
  config:
    bookmarks:
      - Developer:
        - Github:
          - abbr: GH
            href: https://github.com/
    services:
      - Storage:
          - Longhorn:
            href: https://longhorn.k3s.firekatt.ca
      - Media:
          - Plex:
            href: https://plex.k3s.firekatt.ca
          - Sonarr:
            href: https://sonarr.k3s.firekatt.ca
          - Radarr:
            href: https://radarr.k3s.firekatt.ca
          - SABnzbd:
            href: https://sabnzbd.k3s.firekatt.ca
          - Overseerr:
            href: https://overseerr.k3s.firekatt.ca
          - Mylar:
            href: https://mylar.k3s.firekatt.ca
          - Bazarr:
            href: https://bazarr.k3s.firekatt.ca
          - Prowlarr:
            href: https://prowlarr.k3s.firekatt.ca
          - Readarr:
            href: https://readarr.k3s.firekatt.ca
      - Home Automation:
          - Home Assistant:
            href: https://ha.k3s.firekatt.ca
          - ESPHome:
            href: https://esphome.k3s.firekatt.ca
      - My First Group:
          - My First Service:
              href: http://localhost/
              description: Homepage is awesome

      - My Second Group:
          - My Second Service:
              href: http://localhost/
              description: Homepage is the best

      - My Third Group:
          - My Third Service:
              href: http://localhost/
              description: Homepage is 😎
    widgets:
      # show the kubernetes widget, with the cluster summary and individual nodes
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: duckduckgo
          target: _blank
    kubernetes:
      mode: cluster
    settings:

  # The service account is necessary to allow discovery of other services
  serviceAccount:
    create: true
    name: homepage

  # This enables the service account to access the necessary resources
  enableRbac: true

  ingress:
    main:
      enabled: true
      annotations:
        # Example annotations to add Homepage to your Homepage!
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Homepage"
        gethomepage.dev/description: "Dynamically Detected Homepage"
        gethomepage.dev/group: "Dynamic"
        gethomepage.dev/icon: "homepage.png"
      hosts:
        - host: homepage.k3s.firekatt.ca
          paths:
            - path: /
              pathType: Prefix