homepage:
  config:
    settings:
      title: FireBall - FireKatt3 Homepage
      theme: dark
      headerStyle: boxed
      # background: https://wallpapersmug.com/u/12c15c/cityscape-cycle-ride-lets-go-home-art.jpeg
      # cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur
      base: https://homepage.k3s.firekatt.ca/
      target: _self
    bookmarks:
      - Developer:
        - Github:
          - abbr: GH
            href: https://github.com/
    services:
      - Storage:
          - Longhorn:
              href: https://longhorn.k3s.firekatt.ca
              icon: "longhorn.png"
      - Media:
          - Plex:
              href: https://plex.k3s.firekatt.ca
              icon: "plex.png"
          - Sonarr:
              href: https://sonarr.k3s.firekatt.ca
              icon: "sonarr.png"
          - Radarr:
              href: https://radarr.k3s.firekatt.ca
              icon: "radarr.png"
          - SABnzbd:
              href: https://sabnzbd.k3s.firekatt.ca
              icon: "sabnzbd.png"
          - Overseerr:
              href: https://overseerr.k3s.firekatt.ca
              icon: "overseerr.png"
          - Mylar:
              href: https://mylar.k3s.firekatt.ca
              icon: "mylar.png"
          - Bazarr:
              href: https://bazarr.k3s.firekatt.ca
              icon: "bazarr.png"
          - Prowlarr:
              href: https://prowlarr.k3s.firekatt.ca
              icon: "prowlarr.png"
          - Readarr:
              href: https://readarr.k3s.firekatt.ca
              icon: "readarr.png"
      - Home Automation:
          - Home Assistant:
              href: https://ha.k3s.firekatt.ca
              icon: "home-assistant.png"
          - ESPHome:
              href: https://esphome.k3s.firekatt.ca
              icon: "esphome.png"
      - My First Group:
          - My First Service:
              href: http://localhost/
              description: Homepage is awesome

      - My Second Group:
          - My Second Service:
              href: http://localhost/
              description: Homepage is the best

      - My Third Group:
          - My Third Service:
              href: http://localhost/
              description: Homepage is 😎
    widgets:
      # show the kubernetes widget, with the cluster summary and individual nodes
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: duckduckgo
          target: _blank
    kubernetes:
      mode: cluster

  # The service account is necessary to allow discovery of other services
  serviceAccount:
    create: true
    name: homepage

  # This enables the service account to access the necessary resources
  enableRbac: true

  ingress:
    main:
      enabled: true
      annotations:
        # Example annotations to add Homepage to your Homepage!
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Homepage"
        gethomepage.dev/description: "Dynamically Detected Homepage"
        gethomepage.dev/group: "Dynamic"
        gethomepage.dev/icon: "homepage.png"
      hosts:
        - host: homepage.k3s.firekatt.ca
          paths:
            - path: /
              pathType: Prefix