homepage:
  config:
    settings:
      title: FireBall - FireKatt3 Homepage
      color: slate
      theme: dark
      headerStyle: boxed
      # background: https://wallpapersmug.com/u/12c15c/cityscape-cycle-ride-lets-go-home-art.jpeg
      # cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur
      base: https://homepage.k3s.firekatt.ca/
      target: _self

    bookmarks:
      - Developer:
        - Github:
          - abbr: GH
            href: https://github.com/

      - Misc:
        - Royal Bank of Canada:
          - abbr: RB
            href: https://www.rbcroyalbank.com/personal.html
        - Transport Canada:
          - abbr: TC
            href: https://tc.canada.ca/en
        - Kwartzlab OS:
          - abbr: KO
            href: https://kos.kwartzlab.ca/login

    services:
      - Storage:
          - Longhorn:
              href: https://longhorn.k3s.firekatt.ca
              ping: longhorn.k3s.firekatt.ca
              icon: "longhorn.png"
          - Media Synology:
              href: http://10.0.1.241:5000/
              ping: 10.0.1.241
              icon: "synology.png"
          - Backup Synology:
              href: http://10.0.1.242:5000/
              ping: 10.0.1.241
              icon: "synology.png"

      - Media:
          - Plex:
              href: https://plex.k3s.firekatt.ca
              icon: "plex.png"
          - Sonarr:
              href: https://sonarr.k3s.firekatt.ca
              icon: "sonarr.png"
          - Radarr:
              href: https://radarr.k3s.firekatt.ca
              icon: "radarr.png"
          - SABnzbd:
              href: https://sabnzbd.k3s.firekatt.ca
              icon: "sabnzbd.png"
          - Overseerr:
              href: https://overseerr.k3s.firekatt.ca
              icon: "overseerr.png"
          - Mylar:
              href: https://mylar.k3s.firekatt.ca
              icon: "mylar.png"
          - Bazarr:
              href: https://bazarr.k3s.firekatt.ca
              icon: "bazarr.png"
          - Prowlarr:
              href: https://prowlarr.k3s.firekatt.ca
              icon: "prowlarr.png"
          - Readarr:
              href: https://readarr.k3s.firekatt.ca
              icon: "readarr.png"
          - Tautulli:
              href: https://tautulli.k3s.firekatt.ca/
              icon: "tautulli.png"

      - Home Automation:
          - Home Assistant:
              href: https://ha.k3s.firekatt.ca
              icon: "home-assistant.png"
          - ESPHome:
              href: https://esphome.k3s.firekatt.ca
              icon: "esphome.png"
          - Node Red:
              href: https://nodered.k3s.firekatt.ca
              icon: "node-red.png"
          - ZWaveJS2MQTT:
              href: https://zwave.k3s.firekatt.ca/
              icon: "zwavejs2mqtt.png"
          - Zigbee2MQTT:
              href: https://zigbee.k3s.firekatt.ca/
              icon: "zigbee2mqtt.png"
          - ESPHome (Old):
              href: https://esphome.erins.net/
              icon: "esphome.png"

      - Home Lab:
          - Traefik:
              href: https://traefik.k3s.firekatt.ca/
              icon: "traefik.png"
          - Unifi:
              href: https://unifi.ui.com/
              icon: "unifi.png"
          - Unifi (Local):
              href: http://10.0.1.254/
              icon: "unifi.png"
          - Argo CD:
              href: https://argocd.k3s.firekatt.ca/
              icon: "argocd.png"

      - Monitoring:
          - Grafana:
              href: https://grafana.k3s.firekatt.ca/
              icon: "grafana.png"
          - Prometheus:
              href: https://prometheus.k3s.firekatt.ca/
              icon: "prometheus.png"
          - Alert Manager:
              href: https://alertmanager.k3s.firekatt.ca/
              icon: "alertmanager.png"

    widgets:
      # show the kubernetes widget, with the cluster summary and individual nodes
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: duckduckgo
          target: _self
    kubernetes:
      mode: cluster

  # The service account is necessary to allow discovery of other services
  serviceAccount:
    create: true
    name: homepage

  # This enables the service account to access the necessary resources
  enableRbac: true

  ingress:
    main:
      enabled: true
      # annotations:
      #   # Example annotations to add Homepage to your Homepage!
      #   gethomepage.dev/enabled: "true"
      #   gethomepage.dev/name: "Homepage"
      #   gethomepage.dev/description: "Dynamically Detected Homepage"
      #   gethomepage.dev/group: "Dynamic"
      #   gethomepage.dev/icon: "homepage.png"
      hosts:
        - host: homepage.k3s.firekatt.ca
          paths:
            - path: /
              pathType: Prefix