frigate:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    # -- image repository
    repository: blakeblackshear/frigate
    # -- image tag
    # @default -- chart.appVersion
    tag:
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables. See [docs](https://blakeblackshear.github.io/frigate/) for more details.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: UTC
    # -- Set a RTSP password
    # @default -- empty
    FRIGATE_RTSP_PASSWORD: ""

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 5000
        rtmp:
          enabled: true
          port: 1935
          protocol: TCP
          targetPort: 1935

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      hosts:
      - host: frigate.k3s.firekatt.ca
        paths:
        - path: /
          pathType: Prefix

  securityContext:
    # -- (bool) Privileged securityContext may be required if USB devices are accessed directly through the host machine
    privileged: true

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    data:
      enabled: false
      mountPath: /data
    media:
      enabled: false
      mountPath: /media
    # -- Configure a hostPathMount to mount a USB device in the container.
    # @default -- See values.yaml
    usb:
      enabled: true
      type: hostPath
      hostPath: /dev/bus/usb
    # -- Configure a temporary cache. See [docs](https://blakeblackshear.github.io/frigate/) for more details..
    # @default -- See values.yaml
    cache:
      enabled: true
      type: emptyDir
      medium: Memory
      sizeLimit: 1Gi
      mountPath: /dev/shm

  # -- Affinity constraint rules to place the Pod on a specific node.
  # [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
  affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: app
  #           operator: In
  #           values:
  #           - coral-tpu
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k3s-node-01.firekatt.ca

  # -- Configure the resource requests and/or limits for the Pod
  resources: {}
    # requests:
    #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
    #   gpu.intel.com/i915: 1
    #   cpu: 200m
    #   memory: 256Mi
    # limits:
    #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
    #   # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
    #   gpu.intel.com/i915: 1
    #   memory: 4096Mi

  configmap:
    config:
      # -- Store frigate configuration as a ConfigMap
      enabled: true

      # -- See [docs](https://blakeblackshear.github.io/frigate/) for more details.
      # @default -- see URL to default config
      data:
        config.yml: |
          mqtt:
            host: 10.0.1.101
          detectors:
            # Required: name of the detector
            detector_name:
              # Required: type of the detector
              # Frigate provided types include 'cpu', 'edgetpu', and 'openvino' (default: shown below)
              # Additional detector types can also be plugged in.
              # Detectors may require additional configuration.
              # Refer to the Detectors configuration page for more information.
              type: edgetpu
          cameras:
            firelabs_entrance:
              rtmp:
                enabled: true
              ffmpeg:
                inputs:
                  - path: rtsps://10.1.1.254:7441/a88cJPjhGxGvn1Zn?enableSrtp
                    roles:
                      - detect
                      - rtmp
              detect:
                width: 2688
                height: 1512
            firekatt3_front_yard_driveway:
              rtmp:
                enabled: true
              ffmpeg:
                inputs:
                  - path: rtsps://10.0.1.254:7441/H8yEGCAauh000h4l?enableSrtp
                    roles:
                      - detect
                      - rtmp
              detect:
                width: 2688
                height: 1512
              objects:
                track:
                  - person
                  - car
              zones:
                driveway:
                  coordinates: 2688,1512,2688,1224,2509,966,2268,713,1960,435,1342,474,1359,949,1380,1512
                  objects:
                    - person
                    - car
                path:
                  coordinates: 987,960,196,958,0,1026,0,1512,1385,1512,1359,934
                  objects:
                    - person
                yard:
                  coordinates: 1073,486,866,488,607,561,291,626,0,692,0,1020,144,960,951,952,1348,940,1340,471
                  objects:
                    - person
            firekatt3_garage:
              rtmp:
                enabled: true
              ffmpeg:
                inputs:
                  - path: rtsps://10.0.1.254:7441/zz4up51HfNHxl7y5?enableSrtp
                    roles:
                      - detect
                      - rtmp
              detect:
                width: 2688
                height: 1512
              objects:
                track:
                  - person
                  - car
              zones:
                garage:
                  coordinates: 0,1512,2688,1512,2688,0,0,0
                  objects:
                    - person
                    - car
          ffmpeg:
            global_args: -an