#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/koenkk/zigbee2mqtt
  # -- image tag
  tag: 
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://www.zigbee2mqtt.io/information/configuration.html#override-via-environment-variables) for more details.
# @default -- See below
env:
  # -- Set the data folder for Zigbee2MQTT.
  ZIGBEE2MQTT_DATA: /app

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    hosts:
      - host: zigbee2mqtt.k8s.firekatt.ca
        paths:
          - path: /
            pathType: Prefix

securityContext:
  # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
  privileged: true

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 10Gi
  # -- Configure a hostPathMount to mount a USB device in the container.
  # @default -- See values.yaml
  usb:
    enabled: true
    type: hostPath
    hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2400981-if00

tolerations:
  - key: "zwave-zigbee"
    operator: "Equal"
    value: "only"
    effect: "NoSchedule"

# -- Affinity constraint rules to place the Pod on a specific node.
# [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - talos-piwk-01

# -- zigbee2mqtt configuration settings.
# This will be copied into the container's persistent storage at first run only.
# Further configuration should be done in the application itself!
# See [project documentation](https://www.zigbee2mqtt.io/information/configuration.html) for more information.
# @default -- See values.yaml
config:
  version: 4
  mqtt:
    base_topic: zigbee2mqtt
    server: mqtt://10.0.1.101:1883
  serial:
    port: /dev/ttyUSB0
    adapter: deconz
    baudrate: 115200
    rtscts: false
  advanced:
    log_level: info
    channel: 11
    network_key:
      - 145
      - 109
      - 95
      - 208
      - 228
      - 98
      - 37
      - 125
      - 80
      - 89
      - 54
      - 81
      - 114
      - 63
      - 244
      - 62
    pan_id: 25815
    ext_pan_id:
      - 46
      - 213
      - 62
      - 138
      - 245
      - 26
      - 165
      - 85
  frontend:
    enabled: true
    port: 8080
  homeassistant:
    enabled: true
  onboarding: false